export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface py-16 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl p-8 shadow-lg border border-border">
        <h1 className="text-3xl font-bold text-primary mb-6">Terms &amp; Conditions</h1>
        <div className="prose prose-sm text-text-muted space-y-4">
          <p>Last updated: June 2026</p>
          <h2 className="text-lg font-semibold text-primary">1. Acceptance of Terms</h2>
          <p>By accessing and using the Towers Purebred Co. Project Quotation platform, you agree to be bound by these Terms and Conditions.</p>
          <h2 className="text-lg font-semibold text-primary">2. Services</h2>
          <p>Our platform provides AI-powered construction quotation services, including material quantity estimation and cost calculation based on uploaded engineering drawings.</p>
          <h2 className="text-lg font-semibold text-primary">3. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. All activities under your account are your responsibility.</p>
          <h2 className="text-lg font-semibold text-primary">4. Quotation Accuracy</h2>
          <p>All quotations generated by our AI system are estimates. Actual costs may vary based on market conditions, material availability, and project-specific requirements. Final pricing is subject to review by our team.</p>
          <h2 className="text-lg font-semibold text-primary">5. Intellectual Property</h2>
          <p>All uploaded engineering drawings remain the property of the user. Towers Purebred Co. will not share or distribute uploaded documents without explicit consent.</p>
          <h2 className="text-lg font-semibold text-primary">6. Limitation of Liability</h2>
          <p>Towers Purebred Co. shall not be liable for any indirect, incidental, or consequential damages arising from the use of our quotation services.</p>
          <h2 className="text-lg font-semibold text-primary">7. Contact</h2>
          <p>For questions about these terms, please contact us at support@towerspurebred.com.</p>
        </div>
      </div>
    </div>
  );
}
